version: '3.8'
services:
  app:
      image: 'bookshop:latest'
      build:
        context: .
      container_name: springboot_bookstore
      depends_on:
        - db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_book?currentSchema=bookshop&ssl=false
        - SPRING_DATASOURCE_USERNAME=andy
        - SPRING_DATASOURCE_PASSWORD=andy
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      ports:
        - "8080:8080"
  db:
    container_name: postgres_bookstore
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db_book
      POSTGRES_USER: andy
      POSTGRES_PASSWORD: andy
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_bookstore
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: xenotech327@gmail.com
      PGADMIN_DEFAULT_PASSWORD: andy
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "7777:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data: