version: '3.8'
services:
 db:
   container_name: postgres_bookstore
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: postgres_db
     POSTGRES_USER: andy
     POSTGRES_PASSWORD: andy
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - db-data:/var/lib/postgresql/data

 pgadmin:
   container_name: pgadmin4_bookstore
   image: dpage/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: xenotech327@gmail.com
     PGADMIN_DEFAULT_PASSWORD: andy
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "7777:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data: